name: Dagger Checks
on: [push]

jobs:
  checks:
    name: Dagger Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Call Dagger Checks
        uses: dagger/dagger-for-github@v8.3.0
        with:
          check: '**'
          version: 'v0.19.11'
